//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.11 at 01:19:17 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tools.swf.thecybershadow.net/DoABCLayout", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.thecybershadow.swf.tools.doabclayout;
